<a href="https://colab.research.google.com/github/valvasm/MIS433FORREAL/blob/main/assignment_python_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment: Python Basics
We assume you are using Python 3 in this course.

## Question 1

You've learned different data types in Python. Now, let's test your knowledge.

You need to use to format strings.

Write a program using the "f-strings" (https://realpython.com/python-f-strings/) and user input function to convert temperatures from Fahrenheit to Celsius. [Formula: Celsius = (Fahrenheit – 32)*5/9]

Hint: you may need int() or float() function

An example program output:
```
Please enter the temperature in Fahrenheit: 140
140F is 60.0 in Celsius.
```

In [ ]:
# an example of f-strings and user input function
username = input('What\'s your name? ')
print(f'Welcome, {username}!')

What's your name? Marek
Welcome, Marek!


In [1]:
# complete your program here
f = input('Please enter the temperature in Fahrenheit: ')

print(f)

f = float(f)

#Celsius = (Fahrenheit – 32)*5/9
c = (f - 32) * 5/9

print(f'{f}F is {c} in Celsius. ')
#print(str(f)+'F is '+str(c)+' in Celsius. ')

Please enter the temperature in Fahrenheit: 45
45
45.0F is 7.222222222222222 in Celsius. 


Now, do the oppsoite by convert temperatures from Celsius to Fahrenheit.
Another example:
```
Please enter the temperature in Celcius: 60
60C is 140.0 in Fahrenheit.
```

In [3]:
# complete your program here
c = input('Please enter the temperature in Celsius: ')

c = float(c)

f = (c * 9/5) + 32

print(f'{c}C is {f} in Fahrenheit.')

Please enter the temperature in Celsius: 60
60.0C is 140.0 in Fahrenheit.


Next, let's make it a bit challenging by adding conditional statements to convert temperatures to and from Celsius, Fahrenheit. [Formula: Celsius/5 = (Fahrenheit – 32)/9]

An example program output:
```
Please enter the temperature: 60
Is this in Celsius or Fahrenheit? C
60C is 140 in Fahrenheit
```

Another example:
```
Please enter the temperature: 140
Is this Celsius or Fahrenheit? F
140F is 60 in Celsius
```

In [5]:
# complete your program here
d = input('Please enter the temperature: ')
m = input('Is this in Celsius or Fahrenheit? ')

temp = float(d)

unit = m.upper()

if unit == 'C':
    # Convert Celsius to Fahrenheit: F = (C * 9/5) + 32
    result = (temp * 9/5) + 32
    print(f'{temp}C is {result} in Fahrenheit')

elif unit == 'F':
    # Convert Fahrenheit to Celsius: C = (F - 32) * 5/9
    result = (temp - 32) * 5/9
    print(f'{temp}F is {result} in Celsius')

Please enter the temperature: 89
Is this in Celsius or Fahrenheit? c
89.0C is 192.2 in Fahrenheit


## Question 2

Have some fun with strings.

In [ ]:
sentence = "Talk is cheap. Show me the code - Linus Torvalds"

In [ ]:
# Find the length of this sentence.
len(sentence)

48

In [ ]:
# Convert the whole string to lower case.
sentence.lower()

'talk is cheap. show me the code - linus torvalds'

In [12]:
# Extract a substring from the 10th character from left to the 10th character from right.
substring = sentence[9:-10]

print(substring)

heap. Show me the code - Linu


In [14]:
# Split the sentence into a list of substrings by space ' '.
word_list = sentence.split(' ')

print(word_list)

['Talk', 'is', 'cheap.', 'Show', 'me', 'the', 'code', '-', 'Linus', 'Torvalds']


In [15]:
# Given the sentence, output a list of words in lowercase (without punctuations).
clean_list = sentence.replace('.', '').replace('-', '').lower().split()

print(clean_list)

['talk', 'is', 'cheap', 'show', 'me', 'the', 'code', 'linus', 'torvalds']


In [ ]:
# Count the total number of vowels in the sentence.
vowels = ['a','e','i','o','u']
vowels = 'aeiou'
count = 0
for v in vowels:
    print(v, sentence.lower().count(v))
    count += sentence.lower().count(v)
print(f"Total vowels: {count}")

a 3
e 4
i 2
o 3
u 1
Total vowels: 13


In [18]:
# Find the positions (indexes) of all vowels in the sentence.
vowel_positions = []

for i in range(len(sentence)):
    if sentence[i].lower() in vowels:
        vowel_positions.append(i)

print(f"Vowel indexes: {vowel_positions}")
print(f"Total vowels found: {len(vowel_positions)}")

Vowel indexes: [1, 5, 10, 11, 17, 21, 25, 28, 30, 35, 37, 41, 44]
Total vowels found: 13


## Question 3

Review list comprehension if needed: https://realpython.com/list-comprehension-python/

The formula for list comprehension is: `new_list = [expression for member in iterable (if conditional)]`

You need to do the following:

In [19]:
# Use a loop to create a list of 5 cube numbers and print the list：[0, 1, 8, 27, 64]
cubes = []

for i in range(5):
        cubes.append(i**3)

print(cubes)

[0, 1, 8, 27, 64]


In [20]:
# Use list comprehension to create the same list
cubes = [i**3 for i in range(5)]

print(cubes)

[0, 1, 8, 27, 64]


In [21]:
# Find the postions (indexes) of all vowels in a sentence using list comprehension
sentence = "Toto, I\'ve a feeling we\'re not in Kansas anymore. - THE WIZARD OF OZ (1939)"
vowels = 'aeiou'

vowel_positions = [i for i, char in enumerate(sentence) if char.lower() in vowels]

print(vowel_positions)

[1, 3, 6, 9, 11, 14, 15, 17, 22, 25, 28, 31, 35, 38, 41, 45, 47, 54, 57, 59, 63, 66]


In [ ]:
# Use a loop to create a list of first n numbers in the Fibonacci sequence
# [0, 1, 1, 2, 3, 5, 8, ...]
fibonacci = []
n = input('How many numbers do you want? ')
n = int(n)

# add your code here
if n == 1:
  fiboacci = [0]
elif n ==2:
  fibonacci = [0, 1]
elif n > 2:
  fibonacci = [0, 1]
  while len(fibonacci) < n:
    fibonacci.append(fibonacci[-1] + fibonacci[-2])

print(fibonacci)

How many numbers do you want? 2
[0, 1]


## Question 4

This question is about Python dictionary.

|Vaccine|Efficacy|
|-----|-------|
|Pfizer|95%|
|Moderna|95%|
|AstraZeneca|72%|
|Johnson & Johnson|66%|

Source: https://www.biospace.com/article/comparing-covid-19-vaccines-pfizer-biontech-moderna-astrazeneca-oxford-j-and-j-russia-s-sputnik-v/

In [22]:
# Create a dictionary to save the data of vaccines and their efficacy. (save 95% as 0.95)
v_dict = {
    'Pfizer': 0.95,
    'Moderna': 0.95,
    'AstraZeneca': 0.72,
    'Johnson & Johnson': 0.66,
   }

print(v_dict)

{'Pfizer': 0.95, 'Moderna': 0.95, 'AstraZeneca': 0.72, 'Johnson & Johnson': 0.66}


In [23]:
v = input('Which vaccine? ')
# print the efficacy of the vaccine

if v in v_dict:
    print(f"The efficacy of {v} is {v_dict[v]}")
else:
    print("Vaccine not found in our records.")


Which vaccine? Pfizer
The efficacy of Pfizer is 0.95


In [24]:
# add another vaccine 'Sputnik V' with 91.4% efficacy rate to the dictionary
v_dict['Sputnik V'] = 0.914

print(v_dict)

{'Pfizer': 0.95, 'Moderna': 0.95, 'AstraZeneca': 0.72, 'Johnson & Johnson': 0.66, 'Sputnik V': 0.914}


In [25]:
# add another vaccine 'Sinovac' with 50.38% efficacy rate to the dictionary
v_dict['Sinovac'] = 0.5038

print(v_dict)


{'Pfizer': 0.95, 'Moderna': 0.95, 'AstraZeneca': 0.72, 'Johnson & Johnson': 0.66, 'Sputnik V': 0.914, 'Sinovac': 0.5038}


In [26]:
# Print vaccines with efficacy lower than 90%.
for vaccine, efficacy in v_dict.items():
      if efficacy < 0.90:
        print(f"{vaccine} has an efficacy of {efficacy * 100}%")


AstraZeneca has an efficacy of 72.0%
Johnson & Johnson has an efficacy of 66.0%
Sinovac has an efficacy of 50.38%


In [27]:
# delete the Sinovac vaccine from the dictionary.
del v_dict['Sinovac']

print(v_dict)


{'Pfizer': 0.95, 'Moderna': 0.95, 'AstraZeneca': 0.72, 'Johnson & Johnson': 0.66, 'Sputnik V': 0.914}


In [29]:
#Count the occurrence of each alphabet (no space ' ') in this sentence.
sentence = 'the quick brown fox jumps over the lazy dog'

# Save the result in a dictionary
ch_dict = {}
# Use a loop to iterate all characters
# add your code here
for char in sentence:
    if char != ' ':
        if char in ch_dict:
            ch_dict[char] += 1
        else:
            ch_dict[char] = 1

# print the dictionary
print(ch_dict)

{'t': 2, 'h': 2, 'e': 3, 'q': 1, 'u': 2, 'i': 1, 'c': 1, 'k': 1, 'b': 1, 'r': 2, 'o': 4, 'w': 1, 'n': 1, 'f': 1, 'x': 1, 'j': 1, 'm': 1, 'p': 1, 's': 1, 'v': 1, 'l': 1, 'a': 1, 'z': 1, 'y': 1, 'd': 1, 'g': 1}


## Quesion 5

Next, we will practice with Numpy arrays.  

In [30]:
import numpy as np

In [32]:
# create a 1-D array of first 20 positive even numbers (starting with 2)
even_arr = np.array([i for i in range(2, 42, 2)])

print(even_arr)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]


In [33]:
# create a 1-D array of first 20 positive odd numbers (starting with 1)
even_arr = np.array([i for i in range(2, 42, 2)])

print(even_arr)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]


In [34]:
# create a 10x10 array in the following format:
# first row: [0,1,...,9]
# second row: [10,11,...,19]
# ...
# tenth row: [90,91,...,99]
np.array([])

import numpy as np

arr_10x10 = np.array(range(100)).reshape(10, 10)

print(arr_10x10)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [36]:
# Create a 10x10 array of normally distributed random values
# with mean 0 and standard deviation 1
M = np.random.normal(0, 1, size=(10, 10))

print(M.shape)


(10, 10)


In [37]:
# Count the numbers in M with an absolute value greater than 1.
count = (np.abs(M) > 1).sum()

print(count)

27


In [38]:
# Reference: https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html

# Input the number of rows (input an integer >= 3)
r = int(input('Row count: '))

# Input the number of columns (input another integer >= 3)
c = int(input('Column count: '))

# Create a r x c array of random integers between 10 (inclusive) and 20 (exclusive).
# Syntax: np.random.randint(low, high, size)
arr = np.random.randint(10, 20, size=(r, c))

print(arr)

Row count: 8
Column count: 9
[[16 19 12 18 10 14 15 16 10]
 [16 16 14 16 10 16 10 18 15]
 [15 15 11 17 13 18 15 10 19]
 [16 14 11 11 11 14 14 18 10]
 [17 17 19 18 15 14 18 10 17]
 [11 16 19 17 18 12 17 18 17]
 [16 19 19 19 18 12 11 10 19]
 [12 16 16 17 14 13 13 17 15]]


In [39]:
# output the element in the first row and the third column
element = arr[0, 2]

print(element)


12


In [40]:
# output the element in the second row and the last column
element = arr[1, -1]

print(element)


15


In [41]:
# output the second row of the array
second_row = arr[1, :]

print(second_row)


[16 16 14 16 10 16 10 18 15]


In [42]:
# output the second last row of the array
second_last_row = arr[-2, :]

print(second_last_row)


[16 19 19 19 18 12 11 10 19]


In [43]:
# output the second column of the array
second_column = arr[:, 1]

print(second_column)

[19 16 15 14 17 16 19 16]


In [44]:
# output the second last column of the array
second_last_column = arr[:, -2]

print(second_last_column)

[16 18 10 18 10 18 10 17]


In [47]:
# output the upper-left 3x3 sub-array
sub_array = arr[0:3, 0:3]

print(sub_array)

[[16 19 12]
 [16 16 14]
 [15 15 11]]


In [48]:
# output the bottom-left 3x3 sub-array
sub_array = arr[-3:, :3]

print(sub_array)

[[11 16 19]
 [16 19 19]
 [12 16 16]]


In [49]:
# output the upper-right 3x3 sub-array
sub_array = arr[:3, -3:]

print(sub_array)

[[15 16 10]
 [10 18 15]
 [15 10 19]]


In [50]:
# output the bottom-right 3x3 sub-array
sub_array = arr[-3:, -3:]

print(sub_array)

[[17 18 17]
 [11 10 19]
 [13 17 15]]


In [62]:
# Create a 1-D array from 1 to 50 (inclusive)
# Reshape A to a 5x10 array in the following format:
# first row: [1,...,10]
# second row: [11,...,20]
# ...
# fifth row: [41,...,50]
A = np.arange(1, 51)

A = A.reshape(5, 10)

print(A)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]


In [63]:
# add a row [51,...,60] to A
new_row = np.arange(51, 61)

A = np.vstack([A, new_row])

print(A)

print("New shape:", A.shape)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]
 [51 52 53 54 55 56 57 58 59 60]]
New shape: (6, 10)


In [64]:
# split the new A (6x10) to two 3x10 arrays A1 and A2
# np.vsplit(array, indices_or_sections)
A1, A2 = np.vsplit(A, 2)

print("A1 shape:", A1.shape)
print("A2 shape:", A2.shape)

A1 shape: (3, 10)
A2 shape: (3, 10)


In [65]:
# Add 10 to each element of A
A += 10

print(A)

[[11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]
 [51 52 53 54 55 56 57 58 59 60]
 [61 62 63 64 65 66 67 68 69 70]]


In [66]:
# Calculate the square root of each element in A
A = np.sqrt(A)

print(A)

[[3.31662479 3.46410162 3.60555128 3.74165739 3.87298335 4.
  4.12310563 4.24264069 4.35889894 4.47213595]
 [4.58257569 4.69041576 4.79583152 4.89897949 5.         5.09901951
  5.19615242 5.29150262 5.38516481 5.47722558]
 [5.56776436 5.65685425 5.74456265 5.83095189 5.91607978 6.
  6.08276253 6.164414   6.244998   6.32455532]
 [6.40312424 6.4807407  6.55743852 6.63324958 6.70820393 6.78232998
  6.8556546  6.92820323 7.         7.07106781]
 [7.14142843 7.21110255 7.28010989 7.34846923 7.41619849 7.48331477
  7.54983444 7.61577311 7.68114575 7.74596669]
 [7.81024968 7.87400787 7.93725393 8.         8.06225775 8.1240384
  8.18535277 8.24621125 8.30662386 8.36660027]]


In [67]:
# Above, we have created a 10x10 array M of normally distributed random values
# with mean 0 and standard deviation 1
M.shape

(10, 10)

In [68]:
# Print the mean, standard devietion of all numbers in M
print("Mean:", M.mean())
print("Standard Deviation:", M.std())

Mean: 0.07828578192302939
Standard Deviation: 0.9490852888255595


In [69]:
# Print the maximumn, 3rd quartile, median, 1st quartile, and minimum in M
print("Maximum:", np.max(M))
print("3rd Quartile (Q3):", np.percentile(M, 75))
print("Median (Q2):", np.median(M))
print("1st Quartile (Q1):", np.percentile(M, 25))
print("Minimum:", np.min(M))

Maximum: 3.0596221566423143
3rd Quartile (Q3): 0.6851795737007157
Median (Q2): 0.008073813311234003
1st Quartile (Q1): -0.5250542986037368
Minimum: -1.858532260527977
